config/routes.rb
 Rails.application.routes.draw do
  resources :users

  resources :guests

  resources :events

  resources :rsvps

  root 'users#index'

end

app/models/guest.rb
class Guest < ActiveRecord::Base
  belongs_to :users
  has_many :rsvps
  has_many :events, through: :rsvps
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: [:show, :edit, :update, :destroy]

  # GET /guests
  # GET /guests.json
  def index
    @guests = Guest.all
  end

  # GET /guests/1
  # GET /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests
  # POST /guests.json
  def create
    @guest = Guest.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to guests_path, notice: 'Guest was successfully created.' }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1
  # PATCH/PUT /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to @guest, notice: 'Guest was successfully updated.' }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1
  # DELETE /guests/1.json
  def destroy
    @guest.destroy
    respond_to do |format|
      format.html { redirect_to guests_url, notice: 'Guest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guest_params
      params.require(:guest).permit(:name, :phonenumber)
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_for(@guest, :html => {:class => "form-inline"}) do |f| %>
  <% if @guest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul>
      <% @guest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :phonenumber %>:
    <%= f.text_field :phonenumber %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :type => "submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/guests/edit.html.erb
<h1 class="page-header">Editing Guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Show', @guest, :type => "button", :class => "btn btn-primary" %>

app/views/guests/index.html.erb
<h1 class="page-header">Guest Archive</h1>

<table align="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guests.each do |guest| %>
      <tr>
        <td><%= guest.name %></td>
        <td><%= guest.phonenumber %></td>
        <td>&nbsp;<%= link_to '', guest, :class => "fa fa-eye", :style => "color:blue;" %>&nbsp;</td>
        <td><%= link_to '', edit_guest_path(guest), :class => "fa fa-edit", :style => "color:blue;" %>&nbsp;</td>
        <td><%= link_to '', guest, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o", :style => "color:red;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'New Guest', new_guest_path, :type => "button", :class => "btn btn-primary" %>
<br><br>
<%= link_to 'Logout', root_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Add Events', events_path, :type => "button", :class => "btn btn-primary" %>

app/views/guests/new.html.erb
<h1>New guest</h1>

<%= render 'form' %>

<%= link_to 'Back', guests_path, :type => "button", :class => "btn btn-danger" %>

app/views/guests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @guest.name %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @guest.phonenumber %>
</p>

<%= link_to 'Back', guests_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Edit', edit_guest_path(@guest), :type => "button", :class => "btn btn-primary" %>