config/routes.rb
 Rails.application.routes.draw do
  resources :users

  resources :guests

  resources :events

  resources :rsvps

  root 'users#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :guests
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :phonenumber)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user, :html => {:class => "form-inline"}) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>:
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <%= f.label :phonenumber %>:
    <%= f.text_field :phonenumber %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit :type => "submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1 class="page-header">Editing User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Show', @user, :type => "button", :class => "btn btn-primary" %>

app/views/users/index.html.erb
<h1 class="page-header">Listing Users</h1>

<table align="center">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.phonenumber %></td>
        <td>&nbsp;<%= link_to '', user, :class => "fa fa-eye", :style => "color:blue;" %>&nbsp;</td>
        <td><%= link_to '', edit_user_path(user), :class => "fa fa-edit", :style => "color:blue;" %>&nbsp;</td>
        <td><%= link_to '', user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o", :style => "color:red;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path, :type => "button", :class => "btn btn-primary" %>

app/views/users/new.html.erb
<h1 class="page-header">New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path, :type => "button", :class => "btn btn-danger" %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @user.phonenumber %>
</p>

<%= link_to 'Back', users_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Edit', edit_user_path(@user), :type => "button", :class => "btn btn-primary" %> |
<%= link_to 'Add Guests', guests_path(@guest), :type => "button", :class => "btn btn-primary" %> |
<%= link_to 'Add Events', events_path(@event), :type => "button", :class => "btn btn-primary" %>