config/routes.rb
 Rails.application.routes.draw do
  resources :users

  resources :guests

  resources :events

  resources :rsvps

  root 'users#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :rsvps
  has_many :guests, through: :rsvps
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def isAttending(guest_id)
    rsvps = Rsvp.all
    rsvps.each do |rsvp|
      if guest_id == rsvp.guest_id
        if rsvp.answer != nil
          if rsvp.answer == true
            return true
          else
            return false
          end
        else
          return nil
        end
      else
        return "not found"
      end
    end
  end
  helper_method :isAttending

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @guests = @event.guests
  end

  # GET /events/new
  def new
    @event = Event.new
    @guests = Guest.all
  end

  # GET /events/1/edit
  def edit
    @guests = Guest.all
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    if params["invited"]
      invited_ids = params["invited"].map {|id_string| id_string.to_i}
      @event.guest_ids = invited_ids
    end

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    if params["invited"]
      invited_ids = params["invited"].map {|id_string| id_string.to_i}
      @event.guest_ids = invited_ids
      @event.save
    end
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:details, :date, :time_interval, :time_of_last_send, :time_for_first_send)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => {:class => "form-inline"}) do |f| %> 
    <% if @event.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

            <ul>
                <% @event.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
    <div class="field">
        <%= f.label :details %>:
        <%= f.text_area :details %>
    </div>
    <br>
    <div class="field">
        <%= f.label :date %>:
        <%= f.datetime_select(:date, options = { order: [:month, :day, :year, :hour, :minute], start_year: 2014 }, {:class => 'datetime-select'}) %>
    </div>
    <br>
    <div class="field">
        <%= f.label "How often to remind guests (in seconds!)" %>:
        <%= f.number_field :time_interval %>
    </div>
    <br>
    <div class="field">
        <%= f.label :time_for_first_send %>:
        <%= f.datetime_select(:time_for_first_send, options = { order: [:month, :day, :year, :hour, :minute], start_year: 2014 }, {:class => 'datetime-select'}) %>
    </div>
    <br>
    <div class="guests">
    <table align="center">
        <thead>
        <tr>
            <th>Name</th>
            <th>Phone</th>
            <th colspan="3"></th>
        </tr>
        </thead>
        <% @guests.each do |guest| %>
            <tr>
            <td><%= guest.name %></td>
            <td><%= guest.phonenumber %></td>
            <td><label>&nbsp;<%= check_box_tag 'invited[]', guest.id, guest.events.include?(@event) %></label></td>
            </tr>
        <% end %>
    </table>
    </div>
    </br>
    <div class="actions">
        <%= f.submit :type => "submit", :class => "btn btn-primary" %>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="page-header">Editing Event</h1>
<p id="notice"><%= notice %></p>

<%= render 'form' %>

</br>

<%= link_to 'Back', events_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Show', @event, :type => "button", :class => "btn btn-primary" %>

app/views/events/index.html.erb
<h1 class="page-header">Events</h1>

<table align="center">
  <thead>
    <tr>
      <th>Details</th>
      <th>Date</th>
      <th>Time interval</th>
      <th>Time of last send</th>
      <th>Time for first send</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.details %></td>
        <td><%= event.date %></td>
        <td><%= event.time_interval %></td>
        <td><%= event.time_of_last_send %></td>
        <td><%= event.time_for_first_send %></td>
        <td>&nbsp;<%= link_to '', event, :class => "fa fa-eye", :style => "color:blue;" %>&nbsp;</td>
        <td><%= link_to '', edit_event_path(event), :class => "fa fa-edit", :style => "color:blue;" %>&nbsp;</td>
        <td><%= link_to '', event, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o", :style => "color:red;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path, :type => "button", :class => "btn btn-primary" %>
<br><br>
<%= link_to 'Logout', root_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Guest Archive', guests_path, :type => "button", :class => "btn btn-primary" %>

app/views/events/new.html.erb
<h1 class="page-header">New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path, :type => "button", :class => "btn btn-danger" %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Details:</strong>
  <%= @event.details %>
</p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Time interval in seconds:</strong>
  <%= @event.time_interval %>
</p>

<p>
  <strong>Time of last send:</strong>
  <%= @event.time_of_last_send %>
</p>

<p>
  <strong>Time for first send:</strong>
  <%= @event.time_for_first_send %>
</p>

<div class="guests">
<table align="center">
    <thead>
    <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Attending?</th>
    </tr>
    </thead>
    <% @guests.each do |guest| %>
    <% r = isAttending(guest.id) %>
        <tr>
            <td><%= guest.name %></td>
            <td><%= guest.phonenumber %></td>
            <% if r != nil %>
              <% if r == true %>
              <td><%= "yes" %></td>
              <% else%>
              <td><%= "no" %></td>
              <% end %>
            <% else %>
            <td><%= "--" %></td>
            <% end %>
        </tr>
        

    <% end %>
</table>
</div>

<br>
<%= link_to 'Back', events_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Edit', edit_event_path(@event), :type => "button", :class => "btn btn-primary" %>