config/routes.rb
 Rails.application.routes.draw do
  resources :users

  resources :guests

  resources :events

  resources :rsvps

  root 'users#index'

end

app/models/rsvp.rb
class Rsvp < ActiveRecord::Base
  belongs_to :guest
  belongs_to :event
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
  before_action :set_rsvp, only: [:show, :edit, :update, :destroy]

  # GET /rsvps
  # GET /rsvps.json
  def index
    @rsvps = Rsvp.all
  end

  # GET /rsvps/1
  # GET /rsvps/1.json
  def show
  end

  # GET /rsvps/new
  def new
    @rsvp = Rsvp.new
  end

  # GET /rsvps/1/edit
  def edit
  end

  # POST /rsvps
  # POST /rsvps.json
  def create
    @rsvp = Rsvp.new(rsvp_params)

    respond_to do |format|
      if @rsvp.save
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully created.' }
        format.json { render :show, status: :created, location: @rsvp }
      else
        format.html { render :new }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rsvps/1
  # PATCH/PUT /rsvps/1.json
  def update
    respond_to do |format|
      if @rsvp.update(rsvp_params)
        format.html { redirect_to @rsvp, notice: 'Rsvp was successfully updated.' }
        format.json { render :show, status: :ok, location: @rsvp }
      else
        format.html { render :edit }
        format.json { render json: @rsvp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rsvps/1
  # DELETE /rsvps/1.json
  def destroy
    @rsvp.destroy
    respond_to do |format|
      format.html { redirect_to rsvps_url, notice: 'Rsvp was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rsvp
      @rsvp = Rsvp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rsvp_params
      params.require(:rsvp).permit(:user_id, :event_id, :answer)
    end
end

app/helpers/rsvps_helper.rb
module RsvpsHelper
end

app/views/rsvps/_form.html.erb
<%= form_for(@rsvp, :html => {:class => "form-inline"}) do |f| %>
  <% if @rsvp.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rsvp.errors.count, "error") %> prohibited this rsvp from being saved:</h2>

      <ul>
      <% @rsvp.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guest_id %>
    <%= f.number_field :guest_id %>
  </div>
  <div class="field">
    <%= f.label :event_id %>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :answer %><br>
    <%= f.check_box :answer %>
  </div>
  <div class="actions">
    <%= f.submit :type => "submit", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/rsvps/edit.html.erb
<h1>Editing rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Show', @rsvp, :type => "button", :class => "btn btn-primary" %>

app/views/rsvps/index.html.erb
<h1 class="page-header">Listing Rsvps</h1>

<table align="center">
  <thead>
    <tr>
      <th>Guest</th>
      <th>Event</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rsvps.each do |rsvp| %>
      <tr>
        <td><%= rsvp.guest_id %></td>
        <td><%= rsvp.event_id %></td>
        <td><%= rsvp.answer %></td>
        <td><%= link_to '', rsvp, :class => "fa fa-eye", :style => "color:blue;" %></td>
        <td><%= link_to '', edit_rsvp_path(rsvp), :class => "fa fa-edit", :style => "color:blue;" %></td>
        <td><%= link_to '', rsvp, method: :delete, data: { confirm: 'Are you sure?' }, :class => "fa fa-trash-o", :style => "color:red;" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rsvp', new_rsvp_path, :type => "button", :class => "btn btn-primary" %>

app/views/rsvps/new.html.erb
<h1>New rsvp</h1>

<%= render 'form' %>

<%= link_to 'Back', rsvps_path, :type => "button", :class => "btn btn-danger" %>

app/views/rsvps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rsvp.guest_id %>
</p>

<p>
  <strong>Event:</strong>
  <%= @rsvp.event_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @rsvp.answer %>
</p>

<%= link_to 'Back', rsvps_path, :type => "button", :class => "btn btn-danger" %> |
<%= link_to 'Edit', edit_rsvp_path(@rsvp), :type => "button", :class => "btn btn-primary" %>